[package]
name = "memcrapped"
version = "0.1.0"
authors = ["Diogo Osório <diogo.g.osorio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
